version: '3'
services:

  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./front:/usr/src/app/
      - /usr/src/app/node_modules
    environment: 
      NODE_ENV: "developpement"
      BACK_URL: "http://localhost:1337"
  
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    ports:
      - "1337:1337"
    stdin_open: true
    volumes:
      - ./back:/usr/src/app/
      - /usr/src/app/node_modules
    environment: 
      NODE_ENV: "developpement"
      MYSQL_PASSWORD: "azerty"
      FRONT_URL: "*"

  db:
    image: mysql:5.7
    environment:
        MYSQL_HOST: localhost
        MYSQL_DATABASE: database
        MYSQL_ROOT_PASSWORD: "azerty"
    volumes:
        - ./dump:/docker-entrypoint-initdb.d
        - persistent:/var/lib/mysql
    networks:
        - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - db:db
    ports:
        - "8080:80"
    environment:
        MYSQL_ROOT_PASSWORD: ""

volumes:
  persistent: