FROM node:12.18.4-alpine3.11

WORKDIR /usr/src/app
RUN echo "environnement: developpement"

COPY package*.json /usr/src/app/
RUN npm install
RUN npm install -g sails
COPY . /usr/src/app/

EXPOSE 1337
CMD [ "sails", "lift" ]