FROM node:12.18.4-alpine3.11

WORKDIR /usr/src/app/
RUN echo "environnement: developpement"

COPY package*.json /usr/src/app/
RUN npm install
COPY . /usr/src/app/

EXPOSE 3000
CMD [ "npm", "run", "start" ]